2021-02-01 09:32:51,274 INFO: Microblog startup [in /home/muhinyuzi/Desktop/Test/microblog/app/__init__.py:44]
2021-02-01 09:37:31,306 INFO: Microblog startup [in /home/muhinyuzi/Desktop/Test/microblog/app/__init__.py:44]
2021-02-01 09:51:59,989 INFO: Microblog startup [in /home/muhinyuzi/Desktop/Test/microblog/app/__init__.py:44]
2021-02-04 08:16:48,019 INFO: Microblog startup [in /home/muhinyuzi/Desktop/Test/microblog/app/__init__.py:48]
2021-02-04 08:17:04,203 INFO: Microblog startup [in /home/muhinyuzi/Desktop/Test/microblog/app/__init__.py:48]
2021-02-04 08:21:42,069 INFO: Microblog startup [in /home/muhinyuzi/Desktop/Test/microblog/app/__init__.py:48]
2021-02-04 08:23:26,761 INFO: Microblog startup [in /home/muhinyuzi/Desktop/Test/microblog/app/__init__.py:48]
2021-02-04 08:30:43,511 INFO: Microblog startup [in /home/muhinyuzi/Desktop/Test/microblog/app/__init__.py:50]
2021-02-04 08:31:04,307 ERROR: Exception on /index [GET] [in /home/muhinyuzi/Desktop/Test/microblog/env/lib/python3.6/site-packages/flask/app.py:1892]
Traceback (most recent call last):
  File "/home/muhinyuzi/Desktop/Test/microblog/env/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/muhinyuzi/Desktop/Test/microblog/env/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/muhinyuzi/Desktop/Test/microblog/env/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/muhinyuzi/Desktop/Test/microblog/env/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/muhinyuzi/Desktop/Test/microblog/env/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/muhinyuzi/Desktop/Test/microblog/env/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/muhinyuzi/Desktop/Test/microblog/env/lib/python3.6/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/muhinyuzi/Desktop/Test/microblog/app/routes.py", line 36, in index
    prev_url=prev_url)
  File "/home/muhinyuzi/Desktop/Test/microblog/env/lib/python3.6/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/home/muhinyuzi/Desktop/Test/microblog/env/lib/python3.6/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/muhinyuzi/Desktop/Test/microblog/env/lib/python3.6/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/muhinyuzi/Desktop/Test/microblog/env/lib/python3.6/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/muhinyuzi/Desktop/Test/microblog/env/lib/python3.6/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/muhinyuzi/Desktop/Test/microblog/app/templates/index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/muhinyuzi/Desktop/Test/microblog/app/templates/base.html", line 33, in top-level template code
    {% block scripts %}
  File "/home/muhinyuzi/Desktop/Test/microblog/app/templates/base.html", line 34, in block "scripts"
    {{ super() }}
jinja2.exceptions.UndefinedError: there is no parent block called 'scripts'.
2021-02-04 08:38:21,161 INFO: Microblog startup [in /home/muhinyuzi/Desktop/Test/microblog/app/__init__.py:50]
2021-02-04 08:49:49,851 INFO: Microblog startup [in /home/muhinyuzi/Desktop/Test/microblog/app/__init__.py:50]
2021-02-04 08:50:45,318 INFO: Microblog startup [in /home/muhinyuzi/Desktop/Test/microblog/app/__init__.py:50]
2021-02-04 10:00:33,312 INFO: Microblog startup [in /home/muhinyuzi/Desktop/Test/microblog/app/__init__.py:52]
2021-02-04 10:01:51,194 INFO: Microblog startup [in /home/muhinyuzi/Desktop/Test/microblog/app/__init__.py:52]
2021-02-04 10:02:37,661 INFO: Microblog startup [in /home/muhinyuzi/Desktop/Test/microblog/app/__init__.py:52]
2021-02-04 10:11:25,656 INFO: Microblog startup [in /home/muhinyuzi/Desktop/Test/microblog/app/__init__.py:52]
2021-02-04 10:12:18,317 INFO: Microblog startup [in /home/muhinyuzi/Desktop/Test/microblog/app/__init__.py:52]
2021-02-04 10:13:04,901 INFO: Microblog startup [in /home/muhinyuzi/Desktop/Test/microblog/app/__init__.py:52]
2021-02-04 10:13:53,960 INFO: Microblog startup [in /home/muhinyuzi/Desktop/Test/microblog/app/__init__.py:52]
2021-02-04 10:14:01,295 INFO: Microblog startup [in /home/muhinyuzi/Desktop/Test/microblog/app/__init__.py:52]
2021-02-04 10:16:21,636 INFO: Microblog startup [in /home/muhinyuzi/Desktop/Test/microblog/app/__init__.py:52]
2021-02-04 10:18:29,432 INFO: Microblog startup [in /home/muhinyuzi/Desktop/Test/microblog/app/__init__.py:52]
2021-02-04 10:48:33,843 INFO: Microblog startup [in /home/muhinyuzi/Desktop/Test/microblog/app/__init__.py:52]
2021-02-04 10:48:54,406 INFO: Microblog startup [in /home/muhinyuzi/Desktop/Test/microblog/app/__init__.py:52]
2021-02-04 10:49:02,415 INFO: Microblog startup [in /home/muhinyuzi/Desktop/Test/microblog/app/__init__.py:52]
2021-02-04 11:15:20,712 INFO: Microblog startup [in /home/muhinyuzi/Desktop/Test/microblog/app/__init__.py:52]
2021-02-04 11:15:50,681 INFO: Microblog startup [in /home/muhinyuzi/Desktop/Test/microblog/app/__init__.py:52]
2021-02-04 11:16:31,121 INFO: Microblog startup [in /home/muhinyuzi/Desktop/Test/microblog/app/__init__.py:52]
2021-02-04 11:17:01,972 INFO: Microblog startup [in /home/muhinyuzi/Desktop/Test/microblog/app/__init__.py:52]
2021-02-04 11:20:16,764 INFO: Microblog startup [in /home/muhinyuzi/Desktop/Test/microblog/app/__init__.py:52]
2021-02-04 11:20:48,614 INFO: Microblog startup [in /home/muhinyuzi/Desktop/Test/microblog/app/__init__.py:52]
2021-02-05 10:04:37,593 INFO: Microblog startup [in /home/muhinyuzi/Desktop/Test/microblog/app/__init__.py:52]
2021-02-05 10:22:07,064 INFO: Microblog startup [in /home/muhinyuzi/Desktop/Test/microblog/app/__init__.py:52]
2021-02-05 10:22:10,324 ERROR: Exception on /login [GET] [in /home/muhinyuzi/Desktop/Test/microblog/env/lib/python3.6/site-packages/flask/app.py:1892]
Traceback (most recent call last):
  File "/home/muhinyuzi/Desktop/Test/microblog/env/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/muhinyuzi/Desktop/Test/microblog/env/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/muhinyuzi/Desktop/Test/microblog/env/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/muhinyuzi/Desktop/Test/microblog/env/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/muhinyuzi/Desktop/Test/microblog/env/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/muhinyuzi/Desktop/Test/microblog/env/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/muhinyuzi/Desktop/Test/microblog/app/routes.py", line 80, in login
    return render_template('login.html', title=_('Sign In'), form=form)
  File "/home/muhinyuzi/Desktop/Test/microblog/env/lib/python3.6/site-packages/flask/templating.py", line 138, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/home/muhinyuzi/Desktop/Test/microblog/env/lib/python3.6/site-packages/jinja2/environment.py", line 930, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/home/muhinyuzi/Desktop/Test/microblog/env/lib/python3.6/site-packages/jinja2/environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/home/muhinyuzi/Desktop/Test/microblog/env/lib/python3.6/site-packages/jinja2/environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "/home/muhinyuzi/Desktop/Test/microblog/env/lib/python3.6/site-packages/jinja2/loaders.py", line 127, in load
    code = environment.compile(source, name, filename)
  File "/home/muhinyuzi/Desktop/Test/microblog/env/lib/python3.6/site-packages/jinja2/environment.py", line 638, in compile
    self.handle_exception(source=source_hint)
  File "/home/muhinyuzi/Desktop/Test/microblog/env/lib/python3.6/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/muhinyuzi/Desktop/Test/microblog/env/lib/python3.6/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/muhinyuzi/Desktop/Test/microblog/app/templates/login.html", line 18, in template
    {% endblock %}
jinja2.exceptions.TemplateSyntaxError: Encountered unknown tag 'endblock'.
